/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApiV1PendingTxsTransaction {
    #[serde(rename = "length")]
    pub length: Option<i64>,
    #[serde(rename = "type")]
    pub _type: Option<i64>,
    #[serde(rename = "txid")]
    pub txid: Option<String>,
    #[serde(rename = "inner_hash")]
    pub inner_hash: Option<String>,
    #[serde(rename = "sigs")]
    pub sigs: Option<Vec<String>>,
    #[serde(rename = "inputs")]
    pub inputs: Option<Vec<String>>,
    #[serde(rename = "outputs")]
    pub outputs: Option<Vec<::models::ApiV1PendingTxsTransactionOutputs>>,
}

impl ApiV1PendingTxsTransaction {
    pub fn new() -> ApiV1PendingTxsTransaction {
        ApiV1PendingTxsTransaction {
            length: None,
            _type: None,
            txid: None,
            inner_hash: None,
            sigs: None,
            inputs: None,
            outputs: None,
        }
    }
}
