/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApiV1WalletsEntries {
    #[serde(rename = "public_key")]
    pub public_key: Option<String>,
    #[serde(rename = "address")]
    pub address: Option<String>,
}

impl ApiV1WalletsEntries {
    pub fn new() -> ApiV1WalletsEntries {
        ApiV1WalletsEntries {
            public_key: None,
            address: None,
        }
    }
}
