/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApiV1ExplorerAddressInputs {
    #[serde(rename = "owner")]
    pub owner: Option<String>,
    #[serde(rename = "hours")]
    pub hours: Option<i64>,
    #[serde(rename = "calculated_hours")]
    pub calculated_hours: Option<i64>,
    #[serde(rename = "coins")]
    pub coins: Option<String>,
    #[serde(rename = "uxid")]
    pub uxid: Option<String>,
}

impl ApiV1ExplorerAddressInputs {
    pub fn new() -> ApiV1ExplorerAddressInputs {
        ApiV1ExplorerAddressInputs {
            owner: None,
            hours: None,
            calculated_hours: None,
            coins: None,
            uxid: None,
        }
    }
}
