/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApiV1ExplorerAddressOutputs {
    #[serde(rename = "hours")]
    pub hours: Option<i64>,
    #[serde(rename = "dst")]
    pub dst: Option<String>,
    #[serde(rename = "coins")]
    pub coins: Option<String>,
    #[serde(rename = "uxid")]
    pub uxid: Option<String>,
}

impl ApiV1ExplorerAddressOutputs {
    pub fn new() -> ApiV1ExplorerAddressOutputs {
        ApiV1ExplorerAddressOutputs {
            hours: None,
            dst: None,
            coins: None,
            uxid: None,
        }
    }
}
