/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApiV1ExplorerAddressStatus {
    #[serde(rename = "unconfirmed")]
    pub unconfirmed: Option<bool>,
    #[serde(rename = "block_seq")]
    pub block_seq: Option<i64>,
    #[serde(rename = "label")]
    pub label: Option<i64>,
    #[serde(rename = "confirmed")]
    pub confirmed: Option<bool>,
}

impl ApiV1ExplorerAddressStatus {
    pub fn new() -> ApiV1ExplorerAddressStatus {
        ApiV1ExplorerAddressStatus {
            unconfirmed: None,
            block_seq: None,
            label: None,
            confirmed: None,
        }
    }
}
