/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApiV1WalletTransactionTo {
    #[serde(rename = "hours")]
    pub hours: Option<i64>,
    #[serde(rename = "address")]
    pub address: Option<String>,
    #[serde(rename = "coins")]
    pub coins: Option<i64>,
}

impl ApiV1WalletTransactionTo {
    pub fn new() -> ApiV1WalletTransactionTo {
        ApiV1WalletTransactionTo {
            hours: None,
            address: None,
            coins: None,
        }
    }
}
