/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApiV1PendingTxsTransactionOutputs {
    #[serde(rename = "uxid")]
    pub uxid: Option<String>,
    #[serde(rename = "dst")]
    pub dst: Option<String>,
    #[serde(rename = "coins")]
    pub coins: Option<String>,
    #[serde(rename = "hours")]
    pub hours: Option<i64>,
}

impl ApiV1PendingTxsTransactionOutputs {
    pub fn new() -> ApiV1PendingTxsTransactionOutputs {
        ApiV1PendingTxsTransactionOutputs {
            uxid: None,
            dst: None,
            coins: None,
            hours: None,
        }
    }
}
