/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */

/// ApiV1PendingTxsTransaction : BlockTransactionVerbose has readable transaction data for transactions inside a block. It differs from Transaction in that it includes metadata for transaction inputs and the calculated coinhour fee spent by the block

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApiV1PendingTxsTransaction {
    #[serde(rename = "outputs")]
    pub outputs: Option<Vec<::models::ApiV1ExplorerAddressOutputs>>,
    #[serde(rename = "inner_hash")]
    pub inner_hash: Option<String>,
    #[serde(rename = "inputs")]
    pub inputs: Option<Vec<String>>,
    #[serde(rename = "sigs")]
    pub sigs: Option<Vec<String>>,
    #[serde(rename = "length")]
    pub length: Option<i32>,
    #[serde(rename = "txid")]
    pub txid: Option<String>,
    #[serde(rename = "type")]
    pub _type: Option<i32>,
    #[serde(rename = "timestamp")]
    pub timestamp: Option<i32>,
}

impl ApiV1PendingTxsTransaction {
    /// BlockTransactionVerbose has readable transaction data for transactions inside a block. It differs from Transaction in that it includes metadata for transaction inputs and the calculated coinhour fee spent by the block
    pub fn new() -> ApiV1PendingTxsTransaction {
        ApiV1PendingTxsTransaction {
            outputs: None,
            inner_hash: None,
            inputs: None,
            sigs: None,
            length: None,
            txid: None,
            _type: None,
            timestamp: None,
        }
    }
}
