/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ApiV1WalletTransactionWallet {
    #[serde(rename = "unspents")]
    pub unspents: Option<Vec<String>>,
    #[serde(rename = "addresses")]
    pub addresses: Option<Vec<String>>,
    #[serde(rename = "password")]
    pub password: Option<String>,
    #[serde(rename = "id")]
    pub id: Option<String>,
}

impl ApiV1WalletTransactionWallet {
    pub fn new() -> ApiV1WalletTransactionWallet {
        ApiV1WalletTransactionWallet {
            unspents: None,
            addresses: None,
            password: None,
            id: None,
        }
    }
}
