/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Apiv1exploreraddressInputs {
  #[serde(rename = "owner")]
  owner: Option<String>,
  #[serde(rename = "hours")]
  hours: Option<i64>,
  #[serde(rename = "calculated_hours")]
  calculated_hours: Option<i64>,
  #[serde(rename = "coins")]
  coins: Option<String>,
  #[serde(rename = "uxid")]
  uxid: Option<String>
}

impl Apiv1exploreraddressInputs {
  pub fn new() -> Apiv1exploreraddressInputs {
    Apiv1exploreraddressInputs {
      owner: None,
      hours: None,
      calculated_hours: None,
      coins: None,
      uxid: None
    }
  }

  pub fn set_owner(&mut self, owner: String) {
    self.owner = Some(owner);
  }

  pub fn with_owner(mut self, owner: String) -> Apiv1exploreraddressInputs {
    self.owner = Some(owner);
    self
  }

  pub fn owner(&self) -> Option<&String> {
    self.owner.as_ref()
  }

  pub fn reset_owner(&mut self) {
    self.owner = None;
  }

  pub fn set_hours(&mut self, hours: i64) {
    self.hours = Some(hours);
  }

  pub fn with_hours(mut self, hours: i64) -> Apiv1exploreraddressInputs {
    self.hours = Some(hours);
    self
  }

  pub fn hours(&self) -> Option<&i64> {
    self.hours.as_ref()
  }

  pub fn reset_hours(&mut self) {
    self.hours = None;
  }

  pub fn set_calculated_hours(&mut self, calculated_hours: i64) {
    self.calculated_hours = Some(calculated_hours);
  }

  pub fn with_calculated_hours(mut self, calculated_hours: i64) -> Apiv1exploreraddressInputs {
    self.calculated_hours = Some(calculated_hours);
    self
  }

  pub fn calculated_hours(&self) -> Option<&i64> {
    self.calculated_hours.as_ref()
  }

  pub fn reset_calculated_hours(&mut self) {
    self.calculated_hours = None;
  }

  pub fn set_coins(&mut self, coins: String) {
    self.coins = Some(coins);
  }

  pub fn with_coins(mut self, coins: String) -> Apiv1exploreraddressInputs {
    self.coins = Some(coins);
    self
  }

  pub fn coins(&self) -> Option<&String> {
    self.coins.as_ref()
  }

  pub fn reset_coins(&mut self) {
    self.coins = None;
  }

  pub fn set_uxid(&mut self, uxid: String) {
    self.uxid = Some(uxid);
  }

  pub fn with_uxid(mut self, uxid: String) -> Apiv1exploreraddressInputs {
    self.uxid = Some(uxid);
    self
  }

  pub fn uxid(&self) -> Option<&String> {
    self.uxid.as_ref()
  }

  pub fn reset_uxid(&mut self) {
    self.uxid = None;
  }

}



