/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BlockSchema {
    #[serde(rename = "header")]
    pub header: Option<::models::BlockVerboseSchemaHeader>,
    #[serde(rename = "body")]
    pub body: Option<::models::BlockSchemaBody>,
    #[serde(rename = "size")]
    pub size: Option<i32>,
}

impl BlockSchema {
    pub fn new() -> BlockSchema {
        BlockSchema {
            header: None,
            body: None,
            size: None,
        }
    }
}
