/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BlockVerboseSchemaHeader {
    #[serde(rename = "seq")]
    pub seq: Option<i32>,
    #[serde(rename = "timestamp")]
    pub timestamp: Option<i32>,
    #[serde(rename = "fee")]
    pub fee: Option<i32>,
    #[serde(rename = "version")]
    pub version: Option<i32>,
    #[serde(rename = "block_hash")]
    pub block_hash: Option<String>,
    #[serde(rename = "previous_block_hash")]
    pub previous_block_hash: Option<String>,
    #[serde(rename = "tx_body_hash")]
    pub tx_body_hash: Option<String>,
    #[serde(rename = "ux_hash")]
    pub ux_hash: Option<String>,
}

impl BlockVerboseSchemaHeader {
    pub fn new() -> BlockVerboseSchemaHeader {
        BlockVerboseSchemaHeader {
            seq: None,
            timestamp: None,
            fee: None,
            version: None,
            block_hash: None,
            previous_block_hash: None,
            tx_body_hash: None,
            ux_hash: None,
        }
    }
}
