/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BlockVerboseSchemaBody {
    #[serde(rename = "txns")]
    pub txns: Option<Vec<Value>>,
}

impl BlockVerboseSchemaBody {
    pub fn new() -> BlockVerboseSchemaBody {
        BlockVerboseSchemaBody {
            txns: None,
        }
    }
}
