/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2005 {
    /// git branch name
    #[serde(rename = "branch")]
    pub branch: Option<String>,
    /// git commit id
    #[serde(rename = "commit")]
    pub commit: Option<String>,
    /// version number
    #[serde(rename = "version")]
    pub version: Option<String>,
}

impl InlineResponse2005 {
    pub fn new() -> InlineResponse2005 {
        InlineResponse2005 {
            branch: None,
            commit: None,
            version: None,
        }
    }
}
