/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2005 {
    #[serde(rename = "entries")]
    pub entries: Option<Vec<::models::ApiV1WalletsEntries>>,
    #[serde(rename = "meta")]
    pub meta: Option<::models::ApiV1WalletsMeta>,
}

impl InlineResponse2005 {
    pub fn new() -> InlineResponse2005 {
        InlineResponse2005 {
            entries: None,
            meta: None,
        }
    }
}
