/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2005 {
  #[serde(rename = "entries")]
  entries: Option<Vec<::models::Apiv1walletsEntries>>,
  #[serde(rename = "meta")]
  meta: Option<::models::Apiv1walletsMeta>
}

impl InlineResponse2005 {
  pub fn new() -> InlineResponse2005 {
    InlineResponse2005 {
      entries: None,
      meta: None
    }
  }

  pub fn set_entries(&mut self, entries: Vec<::models::Apiv1walletsEntries>) {
    self.entries = Some(entries);
  }

  pub fn with_entries(mut self, entries: Vec<::models::Apiv1walletsEntries>) -> InlineResponse2005 {
    self.entries = Some(entries);
    self
  }

  pub fn entries(&self) -> Option<&Vec<::models::Apiv1walletsEntries>> {
    self.entries.as_ref()
  }

  pub fn reset_entries(&mut self) {
    self.entries = None;
  }

  pub fn set_meta(&mut self, meta: ::models::Apiv1walletsMeta) {
    self.meta = Some(meta);
  }

  pub fn with_meta(mut self, meta: ::models::Apiv1walletsMeta) -> InlineResponse2005 {
    self.meta = Some(meta);
    self
  }

  pub fn meta(&self) -> Option<&::models::Apiv1walletsMeta> {
    self.meta.as_ref()
  }

  pub fn reset_meta(&mut self) {
    self.meta = None;
  }

}



