/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2009 {
    #[serde(rename = "data")]
    pub data: Option<Value>,
}

impl InlineResponse2009 {
    pub fn new() -> InlineResponse2009 {
        InlineResponse2009 {
            data: None,
        }
    }
}
