/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2008Data {
    #[serde(rename = "transaction")]
    pub transaction: Option<::models::Transaction>,
}

impl InlineResponse2008Data {
    pub fn new() -> InlineResponse2008Data {
        InlineResponse2008Data {
            transaction: None,
        }
    }
}
