/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2007Data {
  #[serde(rename = "version")]
  version: Option<i64>
}

impl InlineResponse2007Data {
  pub fn new() -> InlineResponse2007Data {
    InlineResponse2007Data {
      version: None
    }
  }

  pub fn set_version(&mut self, version: i64) {
    self.version = Some(version);
  }

  pub fn with_version(mut self, version: i64) -> InlineResponse2007Data {
    self.version = Some(version);
    self
  }

  pub fn version(&self) -> Option<&i64> {
    self.version.as_ref()
  }

  pub fn reset_version(&mut self) {
    self.version = None;
  }

}



