/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponseDefault {
    #[serde(rename = "code")]
    pub code: Option<i32>,
    #[serde(rename = "message")]
    pub message: Option<String>,
}

impl InlineResponseDefault {
    pub fn new() -> InlineResponseDefault {
        InlineResponseDefault {
            code: None,
            message: None,
        }
    }
}
