/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */

/// InlineResponse2003UnconfirmedVerifyTransaction : Represent unconfirmed transactions

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2003UnconfirmedVerifyTransaction {
    #[serde(rename = "burn_factor")]
    pub burn_factor: Option<i32>,
    #[serde(rename = "max_transaction_size")]
    pub max_transaction_size: Option<i32>,
    #[serde(rename = "max_decimals")]
    pub max_decimals: Option<i32>,
}

impl InlineResponse2003UnconfirmedVerifyTransaction {
    /// Represent unconfirmed transactions
    pub fn new() -> InlineResponse2003UnconfirmedVerifyTransaction {
        InlineResponse2003UnconfirmedVerifyTransaction {
            burn_factor: None,
            max_transaction_size: None,
            max_decimals: None,
        }
    }
}
