/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2004 {
    #[serde(rename = "announced")]
    pub announced: Option<String>,
    #[serde(rename = "is_valid")]
    pub is_valid: Option<bool>,
    #[serde(rename = "checked")]
    pub checked: Option<String>,
    #[serde(rename = "received")]
    pub received: Option<String>,
    #[serde(rename = "transaction")]
    pub transaction: Option<::models::ApiV1PendingTxsTransaction>,
}

impl InlineResponse2004 {
    pub fn new() -> InlineResponse2004 {
        InlineResponse2004 {
            announced: None,
            is_valid: None,
            checked: None,
            received: None,
            transaction: None,
        }
    }
}
