/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse200 {
    #[serde(rename = "hours")]
    pub hours: Option<i64>,
    #[serde(rename = "coins")]
    pub coins: Option<i32>,
    #[serde(rename = "uxid")]
    pub uxid: Option<String>,
    #[serde(rename = "owner_address")]
    pub owner_address: Option<String>,
    #[serde(rename = "spent_block_seq")]
    pub spent_block_seq: Option<i32>,
    #[serde(rename = "spent_tx")]
    pub spent_tx: Option<String>,
    #[serde(rename = "time")]
    pub time: Option<i64>,
    #[serde(rename = "src_block_seq")]
    pub src_block_seq: Option<i64>,
    #[serde(rename = "src_tx")]
    pub src_tx: Option<String>,
}

impl InlineResponse200 {
    pub fn new() -> InlineResponse200 {
        InlineResponse200 {
            hours: None,
            coins: None,
            uxid: None,
            owner_address: None,
            spent_block_seq: None,
            spent_tx: None,
            time: None,
            src_block_seq: None,
            src_tx: None,
        }
    }
}
