/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineObject {
    #[serde(rename = "change_address")]
    pub change_address: Option<String>,
    #[serde(rename = "hours_selection")]
    pub hours_selection: Option<::models::ApiV1WalletTransactionHoursSelection>,
    #[serde(rename = "ignore_unconfirmed")]
    pub ignore_unconfirmed: Option<bool>,
    #[serde(rename = "to")]
    pub to: Option<Vec<::models::ApiV1WalletTransactionTo>>,
    #[serde(rename = "wallet")]
    pub wallet: Option<::models::ApiV1WalletTransactionWallet>,
}

impl InlineObject {
    pub fn new() -> InlineObject {
        InlineObject {
            change_address: None,
            hours_selection: None,
            ignore_unconfirmed: None,
            to: None,
            wallet: None,
        }
    }
}
