/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2007 {
  #[serde(rename = "data")]
  data: Option<::models::InlineResponse2007Data>,
  #[serde(rename = "error")]
  error: Option<Value>
}

impl InlineResponse2007 {
  pub fn new() -> InlineResponse2007 {
    InlineResponse2007 {
      data: None,
      error: None
    }
  }

  pub fn set_data(&mut self, data: ::models::InlineResponse2007Data) {
    self.data = Some(data);
  }

  pub fn with_data(mut self, data: ::models::InlineResponse2007Data) -> InlineResponse2007 {
    self.data = Some(data);
    self
  }

  pub fn data(&self) -> Option<&::models::InlineResponse2007Data> {
    self.data.as_ref()
  }

  pub fn reset_data(&mut self) {
    self.data = None;
  }

  pub fn set_error(&mut self, error: Value) {
    self.error = Some(error);
  }

  pub fn with_error(mut self, error: Value) -> InlineResponse2007 {
    self.error = Some(error);
    self
  }

  pub fn error(&self) -> Option<&Value> {
    self.error.as_ref()
  }

  pub fn reset_error(&mut self) {
    self.error = None;
  }

}



