/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2002 {
    /// CurrentCoinHourSupply is coins hours in non distribution addresses.
    #[serde(rename = "current_coinhour_supply")]
    pub current_coinhour_supply: Option<String>,
    /// Coins distributed beyond the project.
    #[serde(rename = "current_supply")]
    pub current_supply: Option<String>,
    /// Distribution addresses which are locked and do not count towards total supply.
    #[serde(rename = "locked_distribution_addresses")]
    pub locked_distribution_addresses: Option<Vec<String>>,
    /// MaxSupply is the maximum number of coins to be distributed ever.
    #[serde(rename = "max_supply")]
    pub max_supply: Option<String>,
    /// TotalCoinHourSupply is coin hours in all addresses including unlocked distribution addresses.
    #[serde(rename = "total_coinhour_supply")]
    pub total_coinhour_supply: Option<String>,
    /// TotalSupply is CurrentSupply plus coins held by the distribution addresses that are spendable.
    #[serde(rename = "total_supply")]
    pub total_supply: Option<String>,
    /// Distribution addresses which count towards total supply.
    #[serde(rename = "unlocked_distribution_addresses")]
    pub unlocked_distribution_addresses: Option<Vec<String>>,
}

impl InlineResponse2002 {
    pub fn new() -> InlineResponse2002 {
        InlineResponse2002 {
            current_coinhour_supply: None,
            current_supply: None,
            locked_distribution_addresses: None,
            max_supply: None,
            total_coinhour_supply: None,
            total_supply: None,
            unlocked_distribution_addresses: None,
        }
    }
}
