/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2002 {
  #[serde(rename = "outputs")]
  outputs: Option<Vec<::models::Apiv1exploreraddressOutputs>>,
  #[serde(rename = "inner_hash")]
  inner_hash: Option<String>,
  #[serde(rename = "inputs")]
  inputs: Option<Vec<::models::Apiv1exploreraddressInputs>>,
  #[serde(rename = "fee")]
  fee: Option<i32>,
  #[serde(rename = "sigs")]
  sigs: Option<Vec<String>>,
  #[serde(rename = "length")]
  length: Option<i64>,
  #[serde(rename = "txid")]
  txid: Option<String>,
  #[serde(rename = "type")]
  _type: Option<i32>,
  #[serde(rename = "status")]
  status: Option<::models::Apiv1exploreraddressStatus>,
  #[serde(rename = "timestamp")]
  timestamp: Option<i32>
}

impl InlineResponse2002 {
  pub fn new() -> InlineResponse2002 {
    InlineResponse2002 {
      outputs: None,
      inner_hash: None,
      inputs: None,
      fee: None,
      sigs: None,
      length: None,
      txid: None,
      _type: None,
      status: None,
      timestamp: None
    }
  }

  pub fn set_outputs(&mut self, outputs: Vec<::models::Apiv1exploreraddressOutputs>) {
    self.outputs = Some(outputs);
  }

  pub fn with_outputs(mut self, outputs: Vec<::models::Apiv1exploreraddressOutputs>) -> InlineResponse2002 {
    self.outputs = Some(outputs);
    self
  }

  pub fn outputs(&self) -> Option<&Vec<::models::Apiv1exploreraddressOutputs>> {
    self.outputs.as_ref()
  }

  pub fn reset_outputs(&mut self) {
    self.outputs = None;
  }

  pub fn set_inner_hash(&mut self, inner_hash: String) {
    self.inner_hash = Some(inner_hash);
  }

  pub fn with_inner_hash(mut self, inner_hash: String) -> InlineResponse2002 {
    self.inner_hash = Some(inner_hash);
    self
  }

  pub fn inner_hash(&self) -> Option<&String> {
    self.inner_hash.as_ref()
  }

  pub fn reset_inner_hash(&mut self) {
    self.inner_hash = None;
  }

  pub fn set_inputs(&mut self, inputs: Vec<::models::Apiv1exploreraddressInputs>) {
    self.inputs = Some(inputs);
  }

  pub fn with_inputs(mut self, inputs: Vec<::models::Apiv1exploreraddressInputs>) -> InlineResponse2002 {
    self.inputs = Some(inputs);
    self
  }

  pub fn inputs(&self) -> Option<&Vec<::models::Apiv1exploreraddressInputs>> {
    self.inputs.as_ref()
  }

  pub fn reset_inputs(&mut self) {
    self.inputs = None;
  }

  pub fn set_fee(&mut self, fee: i32) {
    self.fee = Some(fee);
  }

  pub fn with_fee(mut self, fee: i32) -> InlineResponse2002 {
    self.fee = Some(fee);
    self
  }

  pub fn fee(&self) -> Option<&i32> {
    self.fee.as_ref()
  }

  pub fn reset_fee(&mut self) {
    self.fee = None;
  }

  pub fn set_sigs(&mut self, sigs: Vec<String>) {
    self.sigs = Some(sigs);
  }

  pub fn with_sigs(mut self, sigs: Vec<String>) -> InlineResponse2002 {
    self.sigs = Some(sigs);
    self
  }

  pub fn sigs(&self) -> Option<&Vec<String>> {
    self.sigs.as_ref()
  }

  pub fn reset_sigs(&mut self) {
    self.sigs = None;
  }

  pub fn set_length(&mut self, length: i64) {
    self.length = Some(length);
  }

  pub fn with_length(mut self, length: i64) -> InlineResponse2002 {
    self.length = Some(length);
    self
  }

  pub fn length(&self) -> Option<&i64> {
    self.length.as_ref()
  }

  pub fn reset_length(&mut self) {
    self.length = None;
  }

  pub fn set_txid(&mut self, txid: String) {
    self.txid = Some(txid);
  }

  pub fn with_txid(mut self, txid: String) -> InlineResponse2002 {
    self.txid = Some(txid);
    self
  }

  pub fn txid(&self) -> Option<&String> {
    self.txid.as_ref()
  }

  pub fn reset_txid(&mut self) {
    self.txid = None;
  }

  pub fn set__type(&mut self, _type: i32) {
    self._type = Some(_type);
  }

  pub fn with__type(mut self, _type: i32) -> InlineResponse2002 {
    self._type = Some(_type);
    self
  }

  pub fn _type(&self) -> Option<&i32> {
    self._type.as_ref()
  }

  pub fn reset__type(&mut self) {
    self._type = None;
  }

  pub fn set_status(&mut self, status: ::models::Apiv1exploreraddressStatus) {
    self.status = Some(status);
  }

  pub fn with_status(mut self, status: ::models::Apiv1exploreraddressStatus) -> InlineResponse2002 {
    self.status = Some(status);
    self
  }

  pub fn status(&self) -> Option<&::models::Apiv1exploreraddressStatus> {
    self.status.as_ref()
  }

  pub fn reset_status(&mut self) {
    self.status = None;
  }

  pub fn set_timestamp(&mut self, timestamp: i32) {
    self.timestamp = Some(timestamp);
  }

  pub fn with_timestamp(mut self, timestamp: i32) -> InlineResponse2002 {
    self.timestamp = Some(timestamp);
    self
  }

  pub fn timestamp(&self) -> Option<&i32> {
    self.timestamp.as_ref()
  }

  pub fn reset_timestamp(&mut self) {
    self.timestamp = None;
  }

}



