/* 
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2001 {
  #[serde(rename = "csrf_token")]
  csrf_token: Option<String>
}

impl InlineResponse2001 {
  pub fn new() -> InlineResponse2001 {
    InlineResponse2001 {
      csrf_token: None
    }
  }

  pub fn set_csrf_token(&mut self, csrf_token: String) {
    self.csrf_token = Some(csrf_token);
  }

  pub fn with_csrf_token(mut self, csrf_token: String) -> InlineResponse2001 {
    self.csrf_token = Some(csrf_token);
    self
  }

  pub fn csrf_token(&self) -> Option<&String> {
    self.csrf_token.as_ref()
  }

  pub fn reset_csrf_token(&mut self) {
    self.csrf_token = None;
  }

}



