/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * OpenAPI spec version: 0.25.1
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2007 {
    #[serde(rename = "data")]
    pub data: Option<::models::InlineResponse2007Data>,
    #[serde(rename = "error")]
    pub error: Option<Value>,
}

impl InlineResponse2007 {
    pub fn new() -> InlineResponse2007 {
        InlineResponse2007 {
            data: None,
            error: None,
        }
    }
}
