/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2004 {
    #[serde(rename = "connections")]
    pub connections: Option<Vec<::models::NetworkConnectionSchema>>,
}

impl InlineResponse2004 {
    pub fn new() -> InlineResponse2004 {
        InlineResponse2004 {
            connections: None,
        }
    }
}
