/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NetworkConnectionSchema {
    #[serde(rename = "address")]
    pub address: Option<String>,
    #[serde(rename = "connected_at")]
    pub connected_at: Option<i64>,
    #[serde(rename = "height")]
    pub height: Option<i64>,
    #[serde(rename = "id")]
    pub id: Option<i64>,
    #[serde(rename = "is_trusted_peer")]
    pub is_trusted_peer: Option<bool>,
    #[serde(rename = "last_received")]
    pub last_received: Option<i64>,
    #[serde(rename = "last_sent")]
    pub last_sent: Option<i64>,
    #[serde(rename = "listen_port")]
    pub listen_port: Option<i32>,
    #[serde(rename = "mirror")]
    pub mirror: Option<i32>,
    #[serde(rename = "outgoing")]
    pub outgoing: Option<bool>,
    #[serde(rename = "state")]
    pub state: Option<String>,
    #[serde(rename = "unconfirmed_verify_transaction")]
    pub unconfirmed_verify_transaction: Option<::models::NetworkConnectionSchemaUnconfirmedVerifyTransaction>,
    #[serde(rename = "user_agent")]
    pub user_agent: Option<String>,
}

impl NetworkConnectionSchema {
    pub fn new() -> NetworkConnectionSchema {
        NetworkConnectionSchema {
            address: None,
            connected_at: None,
            height: None,
            id: None,
            is_trusted_peer: None,
            last_received: None,
            last_sent: None,
            listen_port: None,
            mirror: None,
            outgoing: None,
            state: None,
            unconfirmed_verify_transaction: None,
            user_agent: None,
        }
    }
}
