/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */

/// NetworkConnectionSchemaUnconfirmedVerifyTransaction : Represent unconfirmed transactions

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct NetworkConnectionSchemaUnconfirmedVerifyTransaction {
    #[serde(rename = "burn_factor")]
    pub burn_factor: Option<i32>,
    #[serde(rename = "max_decimals")]
    pub max_decimals: Option<i32>,
    #[serde(rename = "max_transaction_size")]
    pub max_transaction_size: Option<i32>,
}

impl NetworkConnectionSchemaUnconfirmedVerifyTransaction {
    /// Represent unconfirmed transactions
    pub fn new() -> NetworkConnectionSchemaUnconfirmedVerifyTransaction {
        NetworkConnectionSchemaUnconfirmedVerifyTransaction {
            burn_factor: None,
            max_decimals: None,
            max_transaction_size: None,
        }
    }
}
