/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TransactionV2ParamsAddress {
    #[serde(rename = "hours_selection")]
    pub hours_selection: Option<::models::TransactionV2ParamsAddressHoursSelection>,
}

impl TransactionV2ParamsAddress {
    pub fn new() -> TransactionV2ParamsAddress {
        TransactionV2ParamsAddress {
            hours_selection: None,
        }
    }
}
