/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TransactionVerbose {
    #[serde(rename = "time")]
    pub time: Option<i64>,
    #[serde(rename = "status")]
    pub status: Option<::models::TransactionStatus>,
    #[serde(rename = "txn")]
    pub txn: Option<::models::TransactionVerboseTxn>,
}

impl TransactionVerbose {
    pub fn new() -> TransactionVerbose {
        TransactionVerbose {
            time: None,
            status: None,
            txn: None,
        }
    }
}
