/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */

/// TransactionVerboseTxn : TransactionVerbose has readable transaction data. It adds TransactionStatus to a BlockTransactionVerbose

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TransactionVerboseTxn {
    #[serde(rename = "status")]
    pub status: Option<::models::TransactionStatus>,
    #[serde(rename = "fee")]
    pub fee: Option<i64>,
    #[serde(rename = "inner_hash")]
    pub inner_hash: Option<String>,
    #[serde(rename = "inputs")]
    pub inputs: Option<Vec<::models::TransactionVerboseTxnInputs>>,
    #[serde(rename = "length")]
    pub length: Option<i32>,
    #[serde(rename = "outputs")]
    pub outputs: Option<Vec<Value>>,
    #[serde(rename = "sigs")]
    pub sigs: Option<Vec<String>>,
    #[serde(rename = "timestamp")]
    pub timestamp: Option<i64>,
    #[serde(rename = "txid")]
    pub txid: Option<String>,
    #[serde(rename = "type")]
    pub _type: Option<i32>,
}

impl TransactionVerboseTxn {
    /// TransactionVerbose has readable transaction data. It adds TransactionStatus to a BlockTransactionVerbose
    pub fn new() -> TransactionVerboseTxn {
        TransactionVerboseTxn {
            status: None,
            fee: None,
            inner_hash: None,
            inputs: None,
            length: None,
            outputs: None,
            sigs: None,
            timestamp: None,
            txid: None,
            _type: None,
        }
    }
}
