/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TransactionEncoded {
    #[serde(rename = "transaction")]
    pub transaction: Option<::models::ApiV1PendingTxsTransaction>,
    #[serde(rename = "received")]
    pub received: Option<String>,
    #[serde(rename = "checked")]
    pub checked: Option<String>,
    #[serde(rename = "announced")]
    pub announced: Option<String>,
    #[serde(rename = "is_valid")]
    pub is_valid: Option<bool>,
}

impl TransactionEncoded {
    pub fn new() -> TransactionEncoded {
        TransactionEncoded {
            transaction: None,
            received: None,
            checked: None,
            announced: None,
            is_valid: None,
        }
    }
}
