/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TransactionVerboseTxnInputs {
    #[serde(rename = "uxid")]
    pub uxid: Option<String>,
    #[serde(rename = "owner")]
    pub owner: Option<String>,
    #[serde(rename = "coins")]
    pub coins: Option<String>,
    #[serde(rename = "hours")]
    pub hours: Option<i64>,
    #[serde(rename = "calculated_hours")]
    pub calculated_hours: Option<i64>,
}

impl TransactionVerboseTxnInputs {
    pub fn new() -> TransactionVerboseTxnInputs {
        TransactionVerboseTxnInputs {
            uxid: None,
            owner: None,
            coins: None,
            hours: None,
            calculated_hours: None,
        }
    }
}
