/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TransactionV2ParamsUnspent {
    #[serde(rename = "hours_selection")]
    pub hours_selection: Option<::models::TransactionV2ParamsUnspentHoursSelection>,
    #[serde(rename = "unspents")]
    pub unspents: Option<Vec<String>>,
    #[serde(rename = "change_address")]
    pub change_address: Option<String>,
    #[serde(rename = "to")]
    pub to: Option<Vec<::models::TransactionV2ParamsUnspentTo>>,
}

impl TransactionV2ParamsUnspent {
    pub fn new() -> TransactionV2ParamsUnspent {
        TransactionV2ParamsUnspent {
            hours_selection: None,
            unspents: None,
            change_address: None,
            to: None,
        }
    }
}
