/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct TransactionV2ParamsAddressHoursSelection {
    #[serde(rename = "type")]
    pub _type: Option<String>,
}

impl TransactionV2ParamsAddressHoursSelection {
    pub fn new() -> TransactionV2ParamsAddressHoursSelection {
        TransactionV2ParamsAddressHoursSelection {
            _type: None,
        }
    }
}
