/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct WalletTransactionSignRequest {
    #[serde(rename = "wallet_id")]
    pub wallet_id: Option<String>,
    #[serde(rename = "password")]
    pub password: Option<String>,
    #[serde(rename = "encoded_transaction")]
    pub encoded_transaction: Option<String>,
    #[serde(rename = "sign_indexes")]
    pub sign_indexes: Option<Vec<i64>>,
}

impl WalletTransactionSignRequest {
    pub fn new() -> WalletTransactionSignRequest {
        WalletTransactionSignRequest {
            wallet_id: None,
            password: None,
            encoded_transaction: None,
            sign_indexes: None,
        }
    }
}
