/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct WalletTransactionRequestWallet {
    #[serde(rename = "addresses")]
    pub addresses: Option<Vec<String>>,
    #[serde(rename = "id")]
    pub id: Option<String>,
    #[serde(rename = "password")]
    pub password: Option<String>,
    #[serde(rename = "unspents")]
    pub unspents: Option<Vec<String>>,
}

impl WalletTransactionRequestWallet {
    pub fn new() -> WalletTransactionRequestWallet {
        WalletTransactionRequestWallet {
            addresses: None,
            id: None,
            password: None,
            unspents: None,
        }
    }
}
