/*
 * Skycoin REST API.
 *
 * Skycoin is a next-generation cryptocurrency.
 *
 * The version of the OpenAPI document: 0.26.0
 * Contact: contact@skycoin.net
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct WalletTransactionRequest {
    #[serde(rename = "change_address")]
    pub change_address: Option<String>,
    #[serde(rename = "hours_selection")]
    pub hours_selection: Option<::models::WalletTransactionRequestHoursSelection>,
    #[serde(rename = "ignore_unconfirmed")]
    pub ignore_unconfirmed: Option<bool>,
    #[serde(rename = "to")]
    pub to: Option<Vec<Value>>,
    #[serde(rename = "wallet")]
    pub wallet: Option<::models::WalletTransactionRequestWallet>,
}

impl WalletTransactionRequest {
    pub fn new() -> WalletTransactionRequest {
        WalletTransactionRequest {
            change_address: None,
            hours_selection: None,
            ignore_unconfirmed: None,
            to: None,
            wallet: None,
        }
    }
}
